#!/bin/csh
if ( ! -d mti_lib ) then
	vlib mti_lib
endif
vlog testbench_564.sv +define+RTL
vlog ../../02_RTL/MyDesign.v
#vsim -batch -do vsim.do
vsim -c tb_top -pli /mnt/apps/public/COE/synopsys_apps/verdi_vr-2020_12-SP2-1/share/PLI/MODELSIM/LINUX64/novas_fli.so -64 -do "add wave -r *; log -r *; run -all;"
#vsim -c TESTBED -pli /mnt/apps/public/COE/synopsys_apps/verdi_vr-2020_12-SP2-1/share/PLI/MODELSIM/LINUX/novas_fli.so -do "run -all"

