#!/bin/csh
if ( ! -d mti_lib ) then
	vlib mti_lib
endif
vlog TESTBED.vp +define+RTL
vlog RequestQueue.v
#vsim -batch -do vsim.do
vsim -c test_fixture -pli /mnt/apps/public/COE/synopsys_apps/verdi_vr-2020_12-SP2-1/share/PLI/MODELSIM/LINUX64/novas_fli.so -64 -do "run -all"
#vsim -c TESTBED -pli /mnt/apps/public/COE/synopsys_apps/verdi_vr-2020_12-SP2-1/share/PLI/MODELSIM/LINUX/novas_fli.so -do "run -all"

